
services:
  cursoonline.api:
    build:
        context: .
        target: development
    ports:
      - 8080:80
    depends_on:
      - sqlserver
    develop:
      watch:
        - action: rebuild
          path: .
    networks:
      - cursoonline
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:80'

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment: 
      - MSSQL_SA_PASSWORD=CompL3xP455word
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - MSSQL_AGENT_ENABLED=true
    ports:
      - 1433:1433
    networks:
      - cursoonline
    volumes:
      - cursoonline_sqlserver_data:/var/opt/mssql

volumes:
  cursoonline_sqlserver_data:

networks:
  cursoonline:
    driver: bridge
