CREATE DATABASE CursoOnline
GO

USE CursoOnline
GO

CREATE TABLE TipoUsuario
(
	ID INTEGER IDENTITY NOT NULL,
	DESCRICAO VARCHAR(1000) NOT NULL,

	CONSTRAINT PK_TIPOUSUARIO PRIMARY KEY (ID)
) 
GO

CREATE TABLE Usuario
(
	ID INTEGER IDENTITY NOT NULL,
	EMAIL VARCHAR(1000) NOT NULL,
	SENHA_HASH VARBINARY(255) NULL,
	SENHA_SALT VARBINARY(255) NULL,
	CPF VARCHAR(11) NULL,
	ID_TIPO_USUARIO INTEGER NOT NULL,
	SENHA_PROV_CADASTRO varchar(100)

	CONSTRAINT PK_USUARIO PRIMARY KEY (ID),
	CONSTRAINT FK_USUARIO_TIPOUSUARIO FOREIGN KEY (ID_TIPO_USUARIO) REFERENCES TipoUsuario (ID)
) 
GO

CREATE TABLE Aluno
(
	ID INTEGER IDENTITY NOT NULL,
	ID_USUARIO INTEGER NOT NULL,
	RA INTEGER NOT NULL,

	CONSTRAINT PK_ALUNO PRIMARY KEY (ID),
	CONSTRAINT FK_ALUNO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES Usuario (ID),
	CONSTRAINT UQ_USUARIO_ALUNO UNIQUE (ID_USUARIO)
) 
GO

CREATE TABLE Professor
(
	ID INTEGER IDENTITY NOT NULL,
	ID_USUARIO INTEGER NOT NULL,
	
	CONSTRAINT PK_PROFESSOR PRIMARY KEY (ID),
	CONSTRAINT FK_PROFESSOR_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES Usuario (ID),
	CONSTRAINT UQ_USUARIO_PROFESSOR UNIQUE (ID_USUARIO)
) 
GO

CREATE TABLE Curso
(
	ID INTEGER IDENTITY NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	SOBRE VARCHAR(3000) NOT NULL,
	CARGA_HORARIA INTEGER NOT NULL,
	PUBLICO_ALVO INTEGER NOT NULL,
	VALOR DECIMAL(10, 2) NOT NULL,
	ID_PROFESSOR INTEGER NULL,
	APROVADO BIT NULL

	CONSTRAINT PK_CURSO PRIMARY KEY (ID)
)
GO

CREATE TABLE CursoAluno
(
	ID INTEGER IDENTITY NOT NULL,
	ID_CURSO INTEGER NOT NULL,
	ID_ALUNO INTEGER NOT NULL,
	DATA_INICIO DATETIME NULL,
	DATA_FIM DATETIME NULL,
	PROGRESSO_CURSO INTEGER NULL,

	CONSTRAINT PK_CURSO_ALUNO PRIMARY KEY (ID),
	CONSTRAINT FK_CURSOALUNO_CURSO FOREIGN KEY (ID_CURSO) REFERENCES Curso (ID),
	CONSTRAINT FK_CURSOALUNO_ALUNO FOREIGN KEY (ID_ALUNO) REFERENCES Aluno (ID)
) 
GO